#!/bin/bash

# directories
APP_USER_HOME_DIRECTORY="/home/$APP_USER/"
APP_ENV_ROOT_DIRECTORY=$APP_USER_HOME_DIRECTORY"root/"
APP_ENV_DIRECTORY=$APP_USER_HOME_DIRECTORY"env/"
APP_TMP_DIRECTORY=$APP_USER_HOME_DIRECTORY"tmp/"
APP_RUNTIME_DIRECTORY=$APP_USER_HOME_DIRECTORY"runtime/"
APP_RUNTIME_DIRECTORY_PUBLISHER=$APP_RUNTIME_DIRECTORY"publisher/"
APP_RUNTIME_DIRECTORY_SUBSCRIBER=$APP_RUNTIME_DIRECTORY"subscriber/"
APP_RUNTIME_DIRECTORY_MOTION=$APP_RUNTIME_DIRECTORY"motion/"
APP_KEYSTORE_DIRECTORY=$APP_USER_HOME_DIRECTORY"keystores/"
APP_BINARY_DIRECTORY=$APP_USER_HOME_DIRECTORY"binaries/"
APP_CAMERA_DIRECTORY=$APP_USER_HOME_DIRECTORY"camera/"
APP_STORAGE_DIRECTORY=$APP_USER_HOME_DIRECTORY"storage/"

GIT_BINARY_SUBSCRIBER_LINK="https://github.com/shooty215/dirPicSubscriber.git"
GIT_BINARY_PUBLISHER_LINK="https://github.com/shooty215/dirPicPublisher.git"

GIT_BINARY_SUBSCRIBER=$APP_USER_HOME_DIRECTORY"dirPicSubscriber/jars/dirPicSubscriber.jar"
GIT_BINARY_PUBLISHER=$APP_USER_HOME_DIRECTORY"dirPicPublisher/jars/dirPicPublisher.jar"

GIT_BINARY_SUBSCRIBER_SERVICE=$APP_USER_HOME_DIRECTORY"dirPicSubscriber/service/dirpicsubscriber.service"
GIT_BINARY_PUBLISHER_SERVICE=$APP_USER_HOME_DIRECTORY"dirPicPublisher/service/dirpicpublisher.service"

APP_BINARY_SUBSCRIBER=$APP_BINARY_DIRECTORY"dirPicSubscriber.jar"
APP_BINARY_PUBLISHER=$APP_BINARY_DIRECTORY"dirPicPublisher.jar"

APP_BINARY_SUBSCRIBER_START=$APP_BINARY_DIRECTORY"dirPicSubscriber.sh"
APP_BINARY_PUBLISHER_START=$APP_BINARY_DIRECTORY"dirPicPublisher.sh"

APP_BINARY_SUBSCRIBER_START_ACTUAL=$APP_USER_HOME_DIRECTORY"dirPicSubscriber.sh"
APP_BINARY_PUBLISHER_START_ACTUAL=$APP_USER_HOME_DIRECTORY"dirPicPublisher.sh"

APP_BINARY_SUBSCRIBER_START_FILENAME="dirpicsubscriber"
APP_BINARY_PUBLISHER_START_FILENAME="dirpicpublisher"

$CD $APP_USER_HOME_DIRECTORY$DIR_PIC_SUBSCRIBER
$GIT PULL

$CD $APP_USER_HOME_DIRECTORY$DIR_PIC_PUBLISHER
$GIT PULL

## copy binary files from git repository to app directory
$SUDO $COPY $GIT_BINARY_SUBSCRIBER $APP_BINARY_DIRECTORY
$SUDO $COPY $GIT_BINARY_PUBLISHER $APP_BINARY_DIRECTORY
$SUDO $COPY $GIT_BINARY_SUBSCRIBER_SERVICE $APP_BINARY_DIRECTORY
$SUDO $COPY $GIT_BINARY_PUBLISHER_SERVICE $APP_BINARY_DIRECTORY

# move binary shell files to /usr/bin/
$SUDO $MOVE $APP_BINARY_PUBLISHER_START /usr/bin/${APP_BINARY_PUBLISHER_START_FILENAME}
$SUDO $MOVE $APP_BINARY_SUBSCRIBER_START /usr/bin/${APP_BINARY_SUBSCRIBER_START_FILENAME}

### move service files to system.d
$SUDO $COPY $APP_BINARY_SUBSCRIBER_SERVICE $SERVICE_FILES_DIRECTORY
$SUDO $COPY $APP_BINARY_PUBLISHER_SERVICE $SERVICE_FILES_DIRECTORY
